# Site settings
title: My Space    				 
SEOTitle: 我的空间 | My Space    	
header-image: images/spsyha0jrk5.jpg  	
email: zhegao@ln.hk	
description: "Bugatti历史与延展-《涨知识啦》"  		
url: "https://3220534.github.io"    

# Sidebar settings
sidebar: true                          
sidebar-about-description: "布加迪YYDS"
sidebar-avatar:/images/wa13jxxyxsb.JPG 
